### ISSUE TITLE
Failing verification for typed messages signed using MetaMask

### ISSUE THREAD

**Issue by Chipe1** [storyicon/sigverify#2]
Hi, I'm trying to verify a message signed using the javascript library [wagmi](https://wagmi.sh/react/hooks/useSignTypedData) (uses ethers.js) through MetaMask and trying to verify in Go using this project but it fails with the error `there is extra data provided in the message (0 < 1)`. Code to reproduce:

JavaScript code used to create signature:
```
const domain = {
    name: 'My Domain',
} as const
const types = {
    Action: [
        { name: 'type', type: 'string' },
        { name: 'value', type: 'string' },
    ],
} as const;
const value = {
    type: "Change description",
    value: "New value"
} as const
const signed = await signTypedDataAsync({
    domain,
    types,
    value,
});
```

Then I signed the data using MetaMask wallet with address `0xd6F5004d3124Aba6A54813EA69627292d96e9c7d` and got this signed hash `0x5a9df794941046f20a0f024808f5ebe209b6d46893ecb981eadc084c6c26bc1530e3cb7b8cf7305701acb0f9d2432a0ba409589c6fd2108601d22fdbaae3d2bd1c`

Code to verify typed data signature in Go:
```
const ExampleTypedData = `
{
  "types": {
    "Action": [
      {
        "name": "type",
        "type": "string"
      },
      {
        "name": "value",
        "type": "string"
      }
    ]
  },
  "domain": {
    "name": "My Domain"
  },
  "primaryType": "Action",
  "message": {
    "type": "Change description",
    "value": "New value"
  }
}
`

var typedData apitypes.TypedData
if err := json.Unmarshal([]byte(ExampleTypedData), &typedData); err != nil {
	panic(err)
}

valid, err := sigverify.VerifyTypedDataHexSignatureEx(
	ethcommon.HexToAddress("0xd6F5004d3124Aba6A54813EA69627292d96e9c7d"),
	typedData,
	"0x5a9df794941046f20a0f024808f5ebe209b6d46893ecb981eadc084c6c26bc1530e3cb7b8cf7305701acb0f9d2432a0ba409589c6fd2108601d22fdbaae3d2bd1c",
)
fmt.Println(valid, err)
```

Expected the verification to succeed but instead got this line: `false there is extra data provided in the message (0 < 1)`.

Is there something obvious that I'm missing here? Verification of normal string messages works fine using using these libraries.

**Comment by dovydas55** [comment]
im getting same error! Any updates on this issue?

**Comment by Chipe1** [comment]
@dovydas55 This was long ago so I might be mistaken, but I think I was able to solve this by specifying the `EIP712Domain` type under "types" section. This is the snippet of code that we are currently using that works:
```
	typedData := apitypes.TypedData{
		Types: map[string][]apitypes.Type{
			"EIP712Domain": {
				{
					Name: "name",
					Type: "string",
				},
			},
			"Action": {
				{
					Name: "type",
					Type: "string",
				},
				{
					Name: "value",
					Type: "string",
				},
			},
			"Message": {
				{
					Name: "actions",
					Type: "Action[]",
				},
				{
					Name: "timestamp",
					Type: "string",
				},
			},
		},
		Domain: apitypes.TypedDataDomain{
			Name: "<***redacted***>",
		},
		PrimaryType: "Message",
		Message: map[string]interface{}{
			"actions":   actions,
			"timestamp": signedMessage.Message.Timestamp,
		},
	}

	addrs, err := sigverify.RecoveryTypedDataAddressEx(typedData, signature)
```
